### PR TITLE
Added implementations for any and all

### PR DESCRIPTION
**Pull request by aiudirog**
### Description

Added implementations for `any()` and `all()` to complement other builtin implementations

### CODE REVIEW

**Comment by jreese** [comment]
I like the idea of adding these, but I have two main concerns with their design:

1) The short circuit behavior is potentially leaving coroutines and/or tasks unawaited, which will generate a bunch of warnings in the best case, and result in more or less permanent performance hit on the async event loop in the worst case if given tasks. That behavior doesn't generally cause problems for non-async use cases, but has some subtle problems in asyncio. I think it would probably be more predictable to consume all of the objects and not worry about short-circuiting.

2) This does not make any attempt at concurrent execution, which means it would likely be slower than something like `any(await gather(*coros))`. Given my advice above to consume all the awaitables, I'd probably suggest making this use `aioitertools.asyncio.gather(...)` for a concurrency-limited gather, and then just `return all/any(results)`.

**Comment by aiudirog** [comment]
It looks like you are anticipating an iterable which could also contain coroutines which I wasn't. In that case, do we want to support an input format of `AnyIterable[Union[Any, Awaitable[Any]]]` as well?. We could use `maybe_await()` and `gather()` like:

```python
from .asyncio import gather
from .types import MaybeAwaitable  # Union[T, Awaitable[T]]


async def all(itr: AnyIterable[MaybeAwaitable[Any]]) -> bool:
    aws = [maybe_await(i) async for i in iter(itr)]
    return builtins.all(await gather(*aws))


async def any(itr: AnyIterable[MaybeAwaitable[Any]]) -> bool:
    aws = [maybe_await(i) async for i in iter(itr)]
    return builtins.any(await gather(*aws))
```

I also think it might be useful to add a `gather_iter()` helper function like:

```python
from .asyncio import gather
from .types import MaybeAwaitable  # Union[T, Awaitable[T]]


async def all(itr: AnyIterable[MaybeAwaitable[Any]]) -> bool:
    return builtins.all(await gather_iter(itr))


async def any(itr: AnyIterable[MaybeAwaitable[Any]]) -> bool:
    return builtins.any(await gather_iter(itr))


async def gather_iter(itr: AnyIterable[MaybeAwaitable[T]],
                      loop: Optional[asyncio.AbstractEventLoop] = None,
                      return_exceptions: bool = False,
                      limit: int = -1) -> List[T]:
    return await gather(
        *[maybe_await(i) async for i in iter(itr)],
        loop=loop,
        return_exceptions=return_exceptions,
        limit=limit,
    )
```

Thoughts?

**Comment by jreese** [comment]
Both seem like a good compromise, though if you can find a way to have `gather_iter` in the asyncio module alongside the existing `gather` implementation, that would be great.

**Comment by aiudirog** [comment]
> Both seem like a good compromise, though if you can find a way to have `gather_iter` in the asyncio module alongside the existing `gather` implementation, that would be great.

That's my plan but it looks like pylint isn't happy with the required circular import. I'll disable that check for that line.

**Comment by aiudirog** [comment]
@jreese Any more feedback on this PR? Thanks!

**Review by jreese — APPROVED** [review]

**Comment by jreese** [comment]
Thank you!

**Pull request merged**
